// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using sheeps3.Models;
using System;

namespace sheeps3.Migrations
{
    [DbContext(typeof(SheepsEntityFrameworkCoreDbContext))]
    [Migration("20190113024547_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sheeps3.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentDoublers");

                    b.Property<int>("CurrentMonetary");

                    b.Property<string>("Player1");

                    b.Property<string>("Player2");

                    b.Property<string>("Player3");

                    b.Property<string>("Player4");

                    b.Property<string>("Player5");

                    b.Property<string>("Player6");

                    b.Property<string>("Player7");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("sheeps3.Models.GameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CrackCount");

                    b.Property<double>("CurrentPoints");

                    b.Property<int>("GameInt");

                    b.Property<bool>("PlayerActive");

                    b.Property<bool>("PlayerInHand");

                    b.Property<string>("PlayerNickName");

                    b.Property<int>("PlayerPosition");

                    b.Property<int>("Score");

                    b.HasKey("Id");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("sheeps3.Models.Hand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BJBlitz");

                    b.Property<string>("BQBlitz");

                    b.Property<DateTime>("Completed");

                    b.Property<string>("Crack");

                    b.Property<string>("CrackBack");

                    b.Property<string>("Dealer");

                    b.Property<int>("Deals");

                    b.Property<bool>("Doubler");

                    b.Property<int>("GameHandNumber");

                    b.Property<int>("GameInt");

                    b.Property<int>("HandScore");

                    b.Property<string>("HandType");

                    b.Property<string>("Opponent1");

                    b.Property<string>("Opponent2");

                    b.Property<string>("Opponent3");

                    b.Property<string>("Opponent4");

                    b.Property<string>("Partner");

                    b.Property<string>("Picker");

                    b.Property<double>("PointMonetary");

                    b.Property<string>("RJBlitz");

                    b.Property<string>("RQBlitz");

                    b.Property<string>("ReCrack");

                    b.Property<string>("Result");

                    b.HasKey("Id");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("sheeps3.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NickName");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
